# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"\x1d\n\x07Product\x12\x12\n\nid_product\x18\x01 \x01(\x05\"*\n\x13TransactionResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32@\n\x0eProductService\x12.\n\nAddProduct\x12\x08.Product\x1a\x14.TransactionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=17
  _PRODUCT._serialized_end=46
  _TRANSACTIONRESPONSE._serialized_start=48
  _TRANSACTIONRESPONSE._serialized_end=90
  _PRODUCTSERVICE._serialized_start=92
  _PRODUCTSERVICE._serialized_end=156
# @@protoc_insertion_point(module_scope)
