# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import servicios_pb2 as servicios__pb2


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_product = channel.unary_unary(
                '/InventoryService/add_product',
                request_serializer=servicios__pb2.HardRequest.SerializeToString,
                response_deserializer=servicios__pb2.EasyRequest.FromString,
                )
        self.update_quantity = channel.unary_unary(
                '/InventoryService/update_quantity',
                request_serializer=servicios__pb2.HardRequest.SerializeToString,
                response_deserializer=servicios__pb2.EasyRequest.FromString,
                )
        self.get_product_by_name = channel.unary_unary(
                '/InventoryService/get_product_by_name',
                request_serializer=servicios__pb2.EasyRequest.SerializeToString,
                response_deserializer=servicios__pb2.EasyRequest.FromString,
                )
        self.list_products = channel.unary_unary(
                '/InventoryService/list_products',
                request_serializer=servicios__pb2.NoRequest.SerializeToString,
                response_deserializer=servicios__pb2.EasyRequest.FromString,
                )


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_product(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_quantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_product_by_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_products(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add_product': grpc.unary_unary_rpc_method_handler(
                    servicer.add_product,
                    request_deserializer=servicios__pb2.HardRequest.FromString,
                    response_serializer=servicios__pb2.EasyRequest.SerializeToString,
            ),
            'update_quantity': grpc.unary_unary_rpc_method_handler(
                    servicer.update_quantity,
                    request_deserializer=servicios__pb2.HardRequest.FromString,
                    response_serializer=servicios__pb2.EasyRequest.SerializeToString,
            ),
            'get_product_by_name': grpc.unary_unary_rpc_method_handler(
                    servicer.get_product_by_name,
                    request_deserializer=servicios__pb2.EasyRequest.FromString,
                    response_serializer=servicios__pb2.EasyRequest.SerializeToString,
            ),
            'list_products': grpc.unary_unary_rpc_method_handler(
                    servicer.list_products,
                    request_deserializer=servicios__pb2.NoRequest.FromString,
                    response_serializer=servicios__pb2.EasyRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_product(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InventoryService/add_product',
            servicios__pb2.HardRequest.SerializeToString,
            servicios__pb2.EasyRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_quantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InventoryService/update_quantity',
            servicios__pb2.HardRequest.SerializeToString,
            servicios__pb2.EasyRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_product_by_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InventoryService/get_product_by_name',
            servicios__pb2.EasyRequest.SerializeToString,
            servicios__pb2.EasyRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list_products(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InventoryService/list_products',
            servicios__pb2.NoRequest.SerializeToString,
            servicios__pb2.EasyRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
