# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servicios.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fservicios.proto\"\x0b\n\tNoRequest\"\x1e\n\x0b\x45\x61syRequest\x12\x0f\n\x07package\x18\x01 \x01(\t\"1\n\x0bHardRequest\x12\x0f\n\x07package\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t2\xd2\x01\n\x10InventoryService\x12+\n\x0b\x61\x64\x64_product\x12\x0c.HardRequest\x1a\x0c.EasyRequest\"\x00\x12/\n\x0fupdate_quantity\x12\x0c.HardRequest\x1a\x0c.EasyRequest\"\x00\x12\x33\n\x13get_product_by_name\x12\x0c.EasyRequest\x1a\x0c.EasyRequest\"\x00\x12+\n\rlist_products\x12\n.NoRequest\x1a\x0c.EasyRequest\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicios_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOREQUEST._serialized_start=19
  _NOREQUEST._serialized_end=30
  _EASYREQUEST._serialized_start=32
  _EASYREQUEST._serialized_end=62
  _HARDREQUEST._serialized_start=64
  _HARDREQUEST._serialized_end=113
  _INVENTORYSERVICE._serialized_start=116
  _INVENTORYSERVICE._serialized_end=326
# @@protoc_insertion_point(module_scope)
